Week_4/Day_2/timetracking/config/routes.rb
# Rails.application.routes.draw do
#   # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
# end

Rails.application.routes.draw do
  get '/', to: 'site#home'
  get '/contact', to: 'site#contact'
  get '/say_name/:name', to: 'site#say_name'
  get '/calculator', to: 'site#calculator'
  post '/calculate', to: 'site#calculate'

  get '/projects', to: 'projects#index'
  get '/projects/new', to: 'projects#new'
  get '/projects/:id', to: 'projects#show'

  post '/projects', to: 'projects#create'

  get '/projects/:id/time_entries', to: 'time_entries#index'
  get '/projects/:id/time_entries/new', to: "time_entries#new"
  post '/project/:id/time_entries', to: 'time_entries#create', as: :project_time_entries


end

Week_4/Day_2/timetracking/app/models/project.rb
class Project < ApplicationRecord
  has_many :time_entries

  validates :name, presence: true, uniqueness: true, length: {maximum: 30}, format: {with: /\[a-zA-Z\s]/}
end

Week_4/Day_2/timetracking/app/models/time_entry.rb
class TimeEntry < ApplicationRecord
  belongs_to :project

  validates :datetime, presence: true
  validates :hours, presence: true, numericality: true

  validates :minutes, presence: true, numericality: true
end

Week_4/Day_2/timetracking/app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  def index
    @projects = Project.order(created_at: :desc).limit(10)
  end

  def show
    @project = Project.find_by(id: params[:id])
    unless @project
      render 'no_project_found'
    end
    # when you use find, it's more difficult to handle the exception
  end

  def new
    @project = Project.new
    render 'new'
  end

  def create
    @project = Project.new(name: params[:project][:name], description: params[:project][:description])

    @project.save

    redirect_to '/projects/#{@project.id}'
  end
end

Week_4/Day_2/timetracking/app/controllers/site_controller.rb
class SiteController < ApplicationController

  def home
    # render 'home'
  end

  def contact
    render 'contact', layout: 'admin'
  end

  def say_name
    @name = params[:name]
    render 'say_name'
  end

  def calculator
  end

  def calculate
    @num1 = params[:first_num].to_f
    @num2 = params[:second_num].to_f
    @result = @num1 + @num2
    render 'calculate'
  end

end

Week_4/Day_2/timetracking/app/controllers/time_entries_controller.rb
class TimeEntriesController < ApplicationController
  def index
    @project = Project.find(params[:id])
    @time_entries = @project.time_entries
  end

  def new
    @project = Project.find(params[:id])
    @time_entry = @project.time_entries.new
  end

  def create
    @project = Project.find(params[:id])
    @entry = @project.time_entries.create(
    hours: params[:time_entry][:hours],
    minutes: params[:time_entry][:minutes],
    datetime: params[:time_entry][:datetime]
    )

    if @entry
      redirect_to action: 'index',
                  controller: 'time_entries',
                  project_id: @project.id

    else
      render 'new'
    end
  end

end

Week_4/Day_2/timetracking/app/helpers/projects_helper.rb
module ProjectsHelper
end

Week_4/Day_2/timetracking/app/helpers/site_helper.rb
module SiteHelper
end

Week_4/Day_2/timetracking/app/helpers/time_entries_helper.rb
module TimeEntriesHelper
end

Week_4/Day_2/timetracking/app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Timetracking - Admin</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <h1> Admin area - welcome!</h1>
    <%= yield %>
  </body>
</html>

Week_4/Day_2/timetracking/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Timetracking</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

Week_4/Day_2/timetracking/app/views/site/calculate.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <link href='https://fonts.googleapis.com/css?family=Open+Sans:400,300,300italic,400italic,600,700,600italic,700italic,800,800italic' rel='stylesheet' type='text/css'>
    <title></title>
  </head>
  <body>

<h1>Here's the result to your caluculation</h1>

The result of <%= @num1 %> + <%= @num2 %> is <%= @result %>


<%= link_to "Back to the calculator", calculator_path%>

<%= link_to "Back to the homepage", "/"%>

</body>
</html>

Week_4/Day_2/timetracking/app/views/site/calculator.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <link href='https://fonts.googleapis.com/css?family=Open+Sans:400,300,300italic,400italic,600,700,600italic,700italic,800,800italic' rel='stylesheet' type='text/css'>
    <title></title>
  </head>
  <body>


<h1>Welcome to the awesome calculator</h1>
<h2>Here you can add two numbers</h2>

<form action="/calculate" method="post">
  <input type="text" name="first_num" placeholder="First Number">
  <input type="text" name="second_num" placeholder="Second Number">
  <input type="hidden" name="authenticity_token" value="<%=form_authenticity_token%>">
  <button type="submit" name="button">Add</button>

</form>

<%= link_to "Back to the homepage", "/"%>

</body>
</html>

Week_4/Day_2/timetracking/app/views/site/contact.html.erb
<h1>contact@example.com</h1>

Week_4/Day_2/timetracking/app/views/site/home.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <link href='https://fonts.googleapis.com/css?family=Open+Sans:400,300,300italic,400italic,600,700,600italic,700italic,800,800italic' rel='stylesheet' type='text/css'>
    <title></title>
  </head>
  <body>


<h1>Welcome to my awesome rails web application</h1>

<img class="jumping-computer" src="http://www.animatedimages.org/data/media/523/animated-hello-image-0025.gif" border="0" alt="animated-hello-image-0025"/>


<%= link_to "Take me to the calculator", calculator_path%>
<%= link_to "Take me to my projects", projects_path%>


</body>
</html>

Week_4/Day_2/timetracking/app/views/site/say_name.html.erb
<p>
  Hello <%=@name%>
</p>


<!-- <img src="/assets/glasses.gif" alt="Kid removing his sunglasses" /> -->
<%= image_tag "glasses.gif"%>